### ISSUE TITLE
Feature request: specify fields returned by `findplacefromtext` method

### ISSUE THREAD

**Issue by cole007** [boldenamsterdam/googlemapsapi#2]
Google provides ability to specify the fields turned by a findplacefromtext search. 
At present the query only returns a list of placeIds which would require further searches against to qualify. 

Would it be possible to be able to specify optional fields to return with the request, eg something like
`https://example.com/api/googleMaps/place/text/cardiff/name,formatted_address,geometry`

**Comment by cole007** [comment]
A proposed update including new route option and optional `fields` added to API query:

https://gist.github.com/cole007/95d3f07fb65bd9e890f4cd8e9e32a57e

**Comment by cole007** [comment]
Working great from this end.

👌🏻

**Comment by boldenamsterdam** [comment]
Great! Release is on its way :)
